### ISSUE TITLE
IP allow/deny-lists for the server

### ISSUE THREAD

**Issue by bluejekyll** [hickory-dns/hickory-dns#1719]
**Is your feature request related to a problem? Please describe.**

Allow for rejection of requests coming from unwanted IP ranges. The implementation should support ipv4 and ipv6 CIDR formatted configuration. Optionally consider more narrow ranges where CIDR does not properly bound the list.

**Describe the solution you'd like**

Add this to the configuration file for the server. Each protocol handler should be updated to evaluate this list. Rejection of the request and closing with no action taken on the server. There should be a test for each protocol type that ensures the list is being evaluated.

**Comment by dns2utf8** [comment]
Design wise I would go with an allow list only.
Then searching a short list is very fast so we don't need any fancy data structure.
