### ISSUE TITLE
Add new algorithms to the NameserverPool for rotating nameservers used when making queries

### ISSUE THREAD

**Issue by bluejekyll** [hickory-dns/hickory-dns#1721]
**Is your feature request related to a problem? Please describe.**

Some namesevers will rate-limit clients. We should come up with new algorithms and policies for how to choose the a nameserver in the pool for each next query.

**Describe the solution you'd like**

We should use this thread to create requirements. Today's algorithm is pretty basic. It works by reordering the Nameservers on each request, but does not currently offer any form of rate-limiting or forced rotation. Additionally it would be nice to track the latency to each nameserver and use that for prioritizing requests.

**Comment by djc** [comment]
#1920 and #1784 made some progress on this, I think.

**Comment by djc** [comment]
Let's close it.
