### ISSUE TITLE
 Integration with oss-fuzz fuzzing service

### ISSUE THREAD

**Issue by manunio** [hickory-dns/hickory-dns#1790]
Hi, I would like to help integrate this project into [OSS-Fuzz](https://github.com/google/oss-fuzz).

- As an initial step for integration I have created this PR: https://github.com/google/oss-fuzz/pull/8711, it contains necessary logic from an OSS-Fuzz perspective to integrate trust-dns.

- OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects.

- As trust-dns already have cargo-fuzz based fuzzing implemented, this makes it easily compatible with oss-fuzz out of box.

-  If you would like to integrate, the only thing I need is a list of email(s), it must be associated with a google account like 
gmail ([why?](https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication)). by doing that, the     provided email(s) will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats.

- As an alternative, if you don't have a google/gmail id, but still wish to integrate. I can add my mail id for time being and monitor bug/crashes.

- Notice the email(s) affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by bluejekyll** [comment]
Is there an option to have oss-fuzz open Issues directly with the project with the reports you mention, rather than email?

**Comment by bluejekyll** [comment]
No, it should be fine. I have a Google email that can work. Thanks for putting this together!

bluejekyll at gmail will work.

**Comment by djc** [comment]
@manunio can you also add me? I'm djc.ochtman at GMail.
