### ISSUE TITLE
Forward-Resolver returns NOERROR instead of NXDOMAIN

### ISSUE THREAD

**Issue by GeldornOfDragonhill** [hickory-dns/hickory-dns#1891]
**Describe the bug**
If the forward resolver is used an upstream NXDOMAIN is returned as NOERROR.

**To Reproduce**
Resolve something like nothing.example.com via the forward resolver and directly to the forwarded name server.

**Sample Program**
```
#[tokio::main]
async fn main() {
    let mut catalog = Catalog::new();

    let forward_config = ForwardConfig {
        name_servers: NameServerConfigGroup::google(),
        options: Some(ResolverOpts::default())
    };

    let authority = ForwardAuthority::try_from_config(Name::from_str(".").unwrap(), ZoneType::Forward, &forward_config).unwrap();

    catalog.upsert(LowerName::from_str(".").unwrap(), Box::new(Arc::new(authority)) as Box<dyn AuthorityObject>);

    let mut server_future = ServerFuture::new(catalog);
    let udp_socket = UdpSocket::bind(SocketAddr::from_str("0.0.0.0:1153").unwrap()).await.unwrap();
    server_future.register_socket(udp_socket);

    server_future.block_until_done().await.unwrap();
}
```

**Expected behavior**
Both should return NXDOMAIN for nonexisting domains.

**Version:**
Crate: [trust-dns-server]
Version: [4e1dc5d6103f7733a9b55033d0aa03629af9ccd7]

**Additional context**
My guess is that the problem stems from https://github.com/bluejekyll/trust-dns/blob/0b6fefea3fefe1086fed4df6781550462de51553/crates/server/src/authority/error.rs#L51-L53 as the is_nx_domain only tests for LookupError::ResponeCode::NXDomain but not for LookupError::ResolveError => NoRecordsFound.response_code beeing NXDomain.

**Comment by GeldornOfDragonhill** [comment]
If I change the config of the sample to the following, I seems to behave the same way as above:

```
let mut catalog = Catalog::new();

    let mut upstream = NameServerConfig::new(SocketAddr::from((IpAddr::V4(Ipv4Addr::new(8, 8, 8, 8)), 53)), Protocol::Udp);
    upstream.trust_negative_responses = true;

    let forward_config = ForwardConfig {
        name_servers: NameServerConfigGroup::from(vec![upstream]),
        options: Some(ResolverOpts::default())
    };
```

**Comment by djc** [comment]
Sorry, your additional context suggestion does seem like an issue. Want to submit a PR for that?

**Comment by bluejekyll** [comment]
@GeldornOfDragonhill, have you confirmed with other tools that this is indeed an NXDOMAIN and not a valid NOERROR empty response? NXDOMAIN only happens when there is no record of any type at a name, whereas NOERROR with no records is valid for a domain name where there exist other records.

**Comment by GeldornOfDragonhill** [comment]
@djc I'll look into it if I can at least provide a fix for the part I'm using (not too familiar with the entire code base)

@bluejekyll With the above provided sample, I used dig with the local forwarder and directly on the nameserver

```
dig a nothing.example.com -p 1153 @127.0.0.1                    

; <<>> DiG 9.18.11 <<>> a nothing.example.com -p 1153 @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31806
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;nothing.example.com.		IN	A
```

```
dig a nothing.example.com @8.8.8.8   

; <<>> DiG 9.18.11 <<>> a nothing.example.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 3452
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;nothing.example.com.		IN	A

;; AUTHORITY SECTION:
example.com.		1459	IN	SOA	ns.icann.org. noc.dns.icann.org. 2022091205 7200 3600 1209600 3600
```

**Comment by GeldornOfDragonhill** [comment]
@bluejekyll I pushed a crude WIP version of a fix to https://github.com/GeldornOfDragonhill/trust-dns/commit/3f64d1d5e8df2d4660800f45222b7f4cde64d54d - yet I think it can be improved quite a bit, so I'm not yet creating a pull request for it.

- It requires a helper struct to patch the LookupObject trait onto  the Record from the NoRecordsFound structs soa. Do you have any better idea how to connect these?
- The trusted flag in the NoRecordsFound struct does not seem to respect the trust_negative_responses flag from the upstream resolver. Have not dig into that yet - just seems weird to me.
- It duplicates functionality of the is_nx_domain function.

I also wonder if it is valid to respond with a NXDOMAIN without a valid SOA record (e.g. when LookUpError::ResponseCode::NxDomain is set) - simply have not deep enough knowledge of the DNS standard for that to answer.

**Comment by djc** [comment]
@GeldornOfDragonhill thanks for working on this. Please submit your branch as a (possibly draft) PR, which makes it easier to discuss in context.
