### ISSUE TITLE
Add crate feature to support webpki-roots

### ISSUE THREAD

**Issue by MarcelCoding** [hickory-dns/hickory-dns#1905]
**Is your feature request related to a problem? Please describe.**
[webpki-roots](https://crates.io/crates/webpki-roots) provides its own certificate store and is therefore independent on the system store. This would e.g. enable the usage of scratch docker images, as these don't provide their own certificates.

**Describe the solution you'd like**
Add crate feature to support webpki-roots

**Additional context**
Example usage with hyper-rustls: https://github.com/rustls/hyper-rustls/blob/main/src/connector/builder.rs#L77-L86

**Comment by djc** [comment]
Makes sense. Would you be able to submit a PR?

**Comment by MarcelCoding** [comment]
I'll give it a try.

**Comment by cpu** [comment]
Could this be considered resolved by https://github.com/hickory-dns/hickory-dns/pull/2005?
