### ISSUE TITLE
Would be really good to have a few DoH examples.

### ISSUE THREAD

**Issue by marcbrevoort-cyberhive** [hickory-dns/hickory-dns#1970]
Documentation is pretty good for doing insecure DNS requests, but as things get more complex it just glosses over things, making it fairly cumbersome to get things up and running. A few examples on how to use DoH would be most welcome!

**Comment by djc** [comment]
What documentation are you looking at? How do you want to use DoH?

**Comment by marcbrevoort-cyberhive** [comment]
I was looking at https://docs.rs/trust-dns-client/0.23.0/trust_dns_client/https/struct.HttpsClientConnection.html 
The use case is having a client do its own secured DNS requests using DNS over HTTPS.
Eventually I've figured a way to accomplish this (as per my comment at https://github.com/bluejekyll/trust-dns/issues/2050#issuecomment-1759296816), but it was certainly a bit of an adventure to get there!

**Comment by djc** [comment]
Would be great if you can submit a PR with an example and/or some documentation improvements!

**Comment by marcbrevoort-cyberhive** [comment]
As this DoH documentation has now been merged, I suppose this is now complete so I'm closing this issue. Thanks for the pleasant collab!
