### ISSUE TITLE
Failing to read "_acme-challenge" TXT record

### ISSUE THREAD

**Issue by lpotthast** [hickory-dns/hickory-dns#2010]
I'm trying to check that an `_acme-challenge` TXT record is available by performing a `txt_lookup` call. The library returns the following error even if only that `_acme-challenge` record is available.
```
ResolveError { kind: Proto(ProtoError { kind: Msg("Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules })
```
Why?

Additionally: `txt_lookup` returns `Result<TxtLookup, ResolveError>` with `TxtLookup` being iterable but immediately returns an error when simply one of multiple available TXT records is incorrect. Why am I not allowed to iterate overall other records which are/would be correct in the view of this library?

Is there any "insecure" or "unsafe" way to still see get the raw values read? 

Are there some configuration parameters I am missing?

**Comment by djc** [comment]
We were just discussing similar issues in #2009. Are you suggesting this might be a regression in the 0.23.0 release?

This is an error from the idna crate. I'm not exactly sure where/why that is being called here. Unfortunately I won't have much time to investigate, but I'm happy to support you if you have a chance to dig in.

I do agree that it would probably make sense that `TxtLookup` should allow you to iterate over records independently of whether a specific record doesn't validate. Would you be able to send a PR for that?

**Comment by bluejekyll** [comment]
I wonder if we need to stop relying on the `idna` crate. It was an easy way to get a puny code implementation, but it might not have enough flexibility for us?

**Comment by djc** [comment]
From my experience working with the idna crate it is pretty flexible and very optimized, I don't think it's at fault here.

**Comment by delta4chat** [comment]
The error still occurs for parsing a dns message with domain `foo_bar.com`, so sometimes this causes actual problems, such as when querying the SPF of some domain: `dig spf_a0.gsa.gov -t TXT @127.0.0.1 -p 1053`

But parse that DNS query returns this error:
```
cannot convert to hickory Query: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules })
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
```

In other resolvers (such as 8.8.8.8) query this should returns some TXT record with IP ranges.

```
dig spf_a0.gsa.gov -t TXT @8.8.8.8
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 51685
;; Flags: qr rd ra; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; spf_a0.gsa.gov.              IN      TXT

;; ANSWER SECTION:
spf_a0.gsa.gov.         10800   IN      TXT     "v=spf1 ip4:159.142.1.236 ip4:159.142.38.196/30 ip4:159.142.160.13 ip4:159.142.166.247 ip4:159.142.1.214/31 ip4:159.142.1.216 ip4:159.142.1.218/31 ip4:159.142.72.63/30 ip4:159.142.72.68 ip4:159.142.191.80 ip4:159.142.134.75 ~all"

;; Received 272 B
```

**Comment by delta4chat** [comment]
Is there any way or option to bypass this error so that DNS query packets "containing underscores in domains" can be correctly parsed?

**Comment by bluejekyll** [comment]
Given the workaround above, I'm going to close this.
