### ISSUE TITLE
Use AsyncClient across multiple tokio async tasks

### ISSUE THREAD

**Issue by qjmiao** [hickory-dns/hickory-dns#2060]
I'm doing AsyncClient DNS operations in AXUM http handlers.
Currently, AsyncClient is shared across tasks through "let state = Arc::new(Mutex::new(client));"

In handler func, I must "let mut client = state.lock().await;"

Can I drop usage of mutex guard?
Is there any MPSC like approach?

Thanks

**Comment by djc** [comment]
`AsyncClient` already contains a MPSC sender. Cloning it should be cheap.

**Comment by qjmiao** [comment]
> `AsyncClient` already contains a MPSC sender. Cloning it should be cheap.

Cool! it works perfectly after dropping Arc<Mutex>
