### ISSUE TITLE
Unable to have log_level work

### ISSUE THREAD

**Issue by williamdes** [hickory-dns/hickory-dns#2082]
**Describe the bug**

In my config I tried to set `log_level = "Debug"` but it changes nothing to the output.
If I use `--debug` it gives more info at startup but nothing more after.

I am perplex and would like to see the queries like I could do some time before.

**To Reproduce**

`log_level = "Debug"`

Run: `dig @10.222.222.1 emails.mail-server.intranet.` see no new line in logs

**Expected behavior**

See requests in the logs at Debug level

**Version:**
Latest Docker

**Comment by djc** [comment]
Try adding `RUST_LOG=debug` to the environment?

**Comment by williamdes** [comment]
> Try adding `RUST_LOG=debug` to the environment?

Thank you, I will try this
Let's say this issue is closed for now

**Comment by williamdes** [comment]
> Try adding `RUST_LOG=debug` to the environment?

Thanks, it works great
