### ISSUE TITLE
dns-over-tls with dns-over-rustls broken since 0.24

### ISSUE THREAD

**Issue by zonyitoo** [hickory-dns/hickory-dns#2108]
**Describe the bug**

`hickory-resolver` with `dns-over-rustls` is broken since 0.24.

**To Reproduce**

Dependency:

```toml
[dependencies]
hickory-resolver = { version = "0.24", features = [
    "dns-over-tls",
    "dns-over-rustls",
] }
```

Test code, borrowed from library's example:

```rust
use hickory_resolver::config::*;
use hickory_resolver::Resolver;
use std::net::*;

fn main() {
    env_logger::init();

    let resolver =
        Resolver::new(ResolverConfig::cloudflare_tls(), ResolverOpts::default()).unwrap();
    let response = resolver.lookup_ip("www.example.com.").unwrap();
    let address = response.iter().next().expect("no addresses returned!");
    if address.is_ipv4() {
        assert_eq!(address, IpAddr::V4(Ipv4Addr::new(93, 184, 216, 34)));
    } else {
        assert_eq!(
            address,
            IpAddr::V6(Ipv6Addr::new(
                0x2606, 0x2800, 0x220, 0x1, 0x248, 0x1893, 0x25c8, 0x1946
            ))
        );
    }
}
```

**Expected behavior**

`resolver.lookup_ip("www.example.com")` should be able to resolve, but returned error:

```
thread 'main' panicked at src/main.rs:10:59:
called `Result::unwrap()` on an `Err` value: ResolveError { kind: Proto(ProtoError { kind: Io(Kind(ConnectionRefused)) }) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**System:**
 - OS: macOS
 - Architecture: x86_64
 - Version 14.1.2
 - rustc version: rustc 1.74.0 (79e9716c9 2023-11-13)

**Version:**
Crate: resolver
Version: 0.24.0

**Additional context**

Detailed TRACE log: [TRACE.log](https://github.com/hickory-dns/hickory-dns/files/13622991/TRACE.log)

Error doesn't exist if we are using `dns-over-native-tls`.

Ref: shadowsocks/shadowsocks-rust#1378

**Comment by zonyitoo** [comment]
Detailed TRACE log (too large, converted to a plain text file):
[TRACE.log](https://github.com/hickory-dns/hickory-dns/files/13622991/TRACE.log)

**Comment by slatian** [comment]
For me the same happens with all TLS backends on Linux on 0.24.0. Trust 0.23 works just fine.

**Comment by cpu** [comment]
I believe you're hitting the problem described in https://github.com/hickory-dns/hickory-dns/issues/2066:

Try adding the `webpki-roots` feature to your `hickory-resolver` dependency features:

```
[dependencies]
hickory-resolver = { version = "0.24", features = [
    "dns-over-tls",
    "dns-over-rustls",
    "webpki-roots"
] }
```

**Comment by slatian** [comment]
That fixed it for me, thank you! Were those previously included by default?

**Comment by bluejekyll** [comment]
Yes, this had been a default, but it made it complex if folks want to choose to use one or the other. I think the discussion in the other issue talks a bit about a better path forward.
