### ISSUE TITLE
AsyncResolver mode , override RuntimeProvider , if take a little time in function bind_udp , so this function will be called many times repeatedly

### ISSUE THREAD

**Issue by oujl** [hickory-dns/hickory-dns#2110]
**Describe the bug**
I am developing an Android app that uses Hickory DNS. I need to handle the fd special after the UDP socket in DNS. I overloaded the RuntimeProvider, and then I found that it caused a lot of UDP sockets to be created

**To Reproduce**
override RuntimeProvider , take a little time in function bind_udp , so this function will be called many times repeatedly

**Expected behavior**

**System:**
 - OS: [android]
 - Architecture: [arm64]
 - Version [12]
 - rustc version: [1.74.1]

**Version:**
Crate: [resolver]
Version: [0.24.0]

**Additional context**

**Comment by oujl** [comment]
test code like this : 

 impl RuntimeProvider for XXXRuntimeProvider {
        type Handle = TokioHandle;
        type Timer = TokioTime;
        type Udp = TokioUdpSocket;
        type Tcp = AsyncIoTokioAsStd<TokioTcpStream>;

        fn create_handle(&self) -> Self::Handle {
            self.0.clone()
        }

        fn connect_tcp(
            &self,
            server_addr: SocketAddr,
        ) -> Pin<Box<dyn Send + Future<Output = std::io::Result<Self::Tcp>>>> {
            Box::pin(async move {
                TokioTcpStream::connect(server_addr)
                    .await
                    .map(AsyncIoTokioAsStd)
            })
        }

        fn bind_udp(
            &self,
            local_addr: SocketAddr,
            _server_addr: SocketAddr,
        ) -> Pin<Box<dyn Send + Future<Output = std::io::Result<Self::Udp>>>> {
            log::debug!(" DNS UDP bind {} -> {}",local_addr,_server_addr);
            Box::pin(async move {
                tokio::time::sleep(std::time::Duration::from_secs(1)).await;
                let udp = tokio::net::UdpSocket::bind(local_addr).await?;
                Ok(udp)
            })
        }
    }

**Comment by djc** [comment]
Yes, it creates a lot of UDP sockets, and for good reason (it would otherwise be too easy for a MITM attack to spoof DNS responses). Given that you didn't fill out the "Expected behavior" section it's unclear why this is causing an issue for you/what we should do differently.

**Comment by oujl** [comment]
I am writing a VPN type app. Internally, it is necessary to distinguish between proxy traffic and non proxy traffic. I need to label the sockets for proxy traffic before sending data. On Android, it is VpnService # protect Android and Native use local socket communication. Every time DNS resolve is executed, many UDP sockets are created Each socket fd needs to be passed to Android VpnService through the local socket Sometimes I can't handle it. So is there any other API that can avoid creating so many UDP sockets

**Comment by djc** [comment]
There currently is not. Perhaps you can avoid relying on UDP in your configuration?

**Comment by oujl** [comment]
OK。Thank you for your answer
