### ISSUE TITLE
www.hickory-dns.org does not work - 404

### ISSUE THREAD

**Issue by pspacek** [hickory-dns/hickory-dns#2154]
**Describe the bug**
We page https://www.hickory-dns.org/ gives HTTP 404 error.

**Comment by hch12907** [comment]
On a related note, https://trust-dns.org/ should redirect to https://hickory-dns.org as well

**Comment by bluejekyll** [comment]
Ok, I started a documentation project that will be the basis for the initial landing page. This is a work in progress, it's a zola based site. I need to clean up a lot before I'll point the hickory domain here: 
- Landing Page: https://hickory-dns.github.io/hickory-docs/
- User Manual: https://hickory-dns.github.io/hickory-docs/book

**Comment by djc** [comment]
Maybe Oranda could be a better fit?

https://opensource.axo.dev/oranda/

**Comment by bluejekyll** [comment]
Ooh. I hadn’t heard of Oranda. That looks great. I’ll see if I can get that going, maybe simpler.

**Comment by bluejekyll** [comment]
Thanks for that recommendation @djc, got that going much more quickly. There are some loose ends to tie up around automation, but I think it's good for right now.

https://hickory-dns.org

is working again.

**Comment by bluejekyll** [comment]
I'm going to close this as I think this is pretty much resolved. the trust-dns.org will need to be migrated, and that's going to be a little annoying, but I should be able to figure that out at some point.
