### ISSUE TITLE
Missing point of contact for security issues

### ISSUE THREAD

**Issue by pspacek** [hickory-dns/hickory-dns#2159]
It's unclear how to report security issues while keeping all the information confidential.

Examples from other DNS servers:
- https://github.com/PowerDNS/pdns/?tab=security-ov-file#readme
- https://gitlab.isc.org/isc-projects/bind9/-/blob/main/SECURITY.md
- https://www.nlnetlabs.nl/security-report/

**Comment by bluejekyll** [comment]
agreed.

**Comment by djc** [comment]
I've enabled private vuln reporting and drafted a basic initial security policy in #2163.
