### ISSUE TITLE
why hickory-proto 0.24.1 ring dependencies is still 0.16.20

### ISSUE THREAD

**Issue by i18n-now** [hickory-dns/hickory-dns#2186]
I see the project Cargo.toml , ring version is 0.17
but in my /Cargo.lock   , hickory-proto 0.24.1 ring dependencies is still 0.16.20

I want ring 0.17, because ring 0.16.20 not support windows arm
(  https://github.com/briansmith/ring/issues/1167#issuecomment-1745560468 )

```
  [[package]]
  name = "hickory-proto"
  version = "0.24.1"
  source = "registry+https://github.com/rust-lang/crates.io-index"
  checksum = "07698b8420e2f0d6447a436ba999ec85d8fbf2a398bbd737b82cac4a2e96e512"
  dependencies = [
   "async-trait",
   "bytes",
   "cfg-if",
   "data-encoding",
   "enum-as-inner",
   "futures-channel",
   "futures-io",
   "futures-util",
   "h2 0.3.26",
   "http 0.2.12",
   "idna 0.4.0",
   "ipnet",
   "once_cell",
   "rand",
   "ring 0.16.20",
   "rustls 0.21.10",
   "rustls-pemfile 1.0.4",
   "thiserror",
   "tinyvec",
   "tokio",
   "tokio-rustls 0.24.1",
   "tracing",
   "url",
  ]
```

**Comment by djc** [comment]
Because hickory-proto relies on Quinn and Quinn hasn't been upgraded to *ring* 0.17. See https://github.com/quinn-rs/quinn/pull/1715 / https://github.com/quinn-rs/quinn/issues/1737.

**Comment by bluejekyll** [comment]
please see: #2206

**Comment by i18n-now** [comment]
@djc @bluejekyll  Quinn release a version , can hickory upgrade ?

**Comment by djc** [comment]
See #2217.
