### ISSUE TITLE
Allow passing in a custom client UDP socket to send data from

### ISSUE THREAD

**Issue by jamilbk** [hickory-dns/hickory-dns#2220]
**Is your feature request related to a problem? Please describe.**
We use hickory (thanks for the library!) to send DNS requests from a VPN tunnel process. If the server we're sending the requests to happens to be in the VPN's routing table (for example, `0.0.0.0/0` for full-route tunneling), a packet loop ensues and the request never reaches the server. This is because we have no control over the socket created by hickory to send the query from.

**Describe the solution you'd like**
It would be great if there was some way to pass in our own socket so that we can configure it as necessary to prevent packet loops. Another option would be to somehow return or expose a function for "getting at" the socket so we can apply the necessary config to it then.

**Describe alternatives you've considered**
Forking hickory to implement our own patch.

**Additional context**
This would be mainly used for Android and Linux platforms that don't have automatic packet loop detection, and instead rely on [`protect`](https://developer.android.com/reference/android/net/VpnService#protect(java.net.Socket)) in Android and `fwmark` in Linux to signal to the routing table **not** to route the packet back into the VPN interface. Apple's [NECP](https://forums.developer.apple.com/forums/thread/725715) seems to automagically prevent this case for Apple platforms (macOS / iOS tested).

**Comment by djc** [comment]
Which library are you using? Are you able to use a custom [`RuntimeProvider`](https://docs.rs/hickory-resolver/latest/hickory_resolver/name_server/trait.RuntimeProvider.html) for this?

**Comment by fmartinsons** [comment]
Ok that was fairly easy thanks to [this example](https://github.com/hickory-dns/hickory-dns/blob/main/crates/resolver/examples/custom_provider.rs) I managed to use bind_device to the socket returned by bind_udp trait method and it perfectly fit what I wanted.

Thank you very much @djc for the help.
