### ISSUE TITLE
tag/publish a 0.25 pre-release?

### ISSUE THREAD

**Issue by cpu** [hickory-dns/hickory-dns#2229]
Hi folks,

Would you be willing to tag/publish a 0.25 release candidate/pre-release?

**Is your feature request related to a problem? Please describe.**

In Rustls we need the fixes from https://github.com/hickory-dns/hickory-dns/pull/2183 to complete our [client side ECH support](https://github.com/rustls/rustls/pull/1718) work.

We would be happy to take a temporary Cargo `patch` to use the unreleased code in `main` with the fix applied, but unfortunately this isn't feasible with our MSRV being 1.63 as it causes [build errors](https://github.com/rustls/rustls/actions/runs/9367579958/job/25794199345?pr=1718) for the MSRV task.

The root cause is a little bit subtle: we only use this dependency in our `examples` and `connect-tests` crates, where we don't enforce a MSRV but because Cargo patches are specified at the workspace level, the build of the `rustls` crate where we _do_ enforce MSRV must resolve the patch (even though it's unused). Resolving the patch is only possible with Rust 1.64+ because of this crate's use of workspace inheritance. The net result is that in order to use a patch, we would have to change our MSRV to 1.64 and we're not presently able to do that (we try to track Debian stable, which is still on 1.63).

**Describe the solution you'd like**

A published 0.25-rc0 or similarly named pre-release made available. This would allow us to update the `connect-test` and `example` crates to depend directly on this published version. That in turn would let us drop the problematic patch.

**Describe alternatives you've considered**

* We could update our MSRV, but it's a tough sell for a dependency we aren't using in the main crate.
* We could wait for a final 0.25 release, but since the project is collecting up other breaking changes this may be blocked for some time.
* We could backport the SVCB fixes to trust-dns 0.22, but this is a bit tricky because of unrelated code drift and would mean we have to regress our example code to use the old trust-dns names & APIs.

**Additional context**

Some additional discussion [in this comment thread](https://github.com/rustls/rustls/pull/1718#discussion_r1626195490). A final 0.25 release is being tracked in https://github.com/hickory-dns/hickory-dns/issues/2206

Thanks!

**Comment by djc** [comment]
I think #2217 is the only real blocker for a final release, so if you were able to have a look at that that would be very welcome.

But if not, it's probably fine to just do a pre-release.

**Comment by cpu** [comment]
> But if not, it's probably fine to just do a pre-release.

I'm still open to supporting 2217 but IMO it's not close enough to mergeable that I want to block my downstream work.

Do you think you or @bluejekyll could publish a pre-release in the next few days?

**Comment by bluejekyll** [comment]
0.25.0-alpha.1 just published. Thanks for the request @cpu.

We should probably discuss a release policy for the project. I just realized how long ago the last release was why I was writing up the changelog.

**Comment by cpu** [comment]
Thank you! Much appreciated :-)
