### ISSUE TITLE
What is the reason for NextRandomUdpSocket?

### ISSUE THREAD

**Issue by Luap99** [hickory-dns/hickory-dns#2230]
We got a issue[1] where a user has basically all udp ports in the range bound thus causing NextRandomUdpSocket to fail to bind a free port. I see that the default range was changed in https://github.com/hickory-dns/hickory-dns/commit/8f05d14eed53c488ee14fa860ef68cad352168ff so I guess it should very unlikely to hit this but I wonder what the reason for doing this in the first place is? 
Why does it not just pass port 0 to the kernel and let the kernel assign a free port? This seems more robust and it doesn't require a lot of retires to find a free port. I tried to look in the git history but is seem this logic was added very early on without explanation why this approach was chosen.
Also on linux at least there is the net.ipv4.ip_local_port_range sysctl to specify the ephemeral port range but this logic seems to ignore this as well.

I guess we can implement our own SocketType that does that so it shouldn't be a big problem but I was interested in knowing why it is like this before I do so.

[1] https://github.com/containers/aardvark-dns/issues/473

**Comment by bluejekyll** [comment]
This is designed to mitigate DNS cache poisoning attacks, you can read more here: http://www.unixwiz.net/techtips/iguide-kaminsky-dns-vuln.html

randomizing the ports used adds more entropy to the randomness of the message id, making response spoofing over UDP harder for attackers.

**Comment by Luap99** [comment]
> This is designed to mitigate DNS cache poisoning attacks, you can read more here: http://www.unixwiz.net/techtips/iguide-kaminsky-dns-vuln.html
> 
> randomizing the ports used adds more entropy to the randomness of the message id, making response spoofing over UDP harder for attackers.

Thanks, yes that sounds good. Would it make sense instead of of aborting after the 10 tries to do the bind with port 0 instead? That would increase the risk a bit I guess but if a users only has a few free udp ports it should at least work and the kernel will give us that free port. And if there only a few ports free the other side could try to predict them regardless I think.

I don't know what causes all the retires exactly but I see thousands of bind syscalls until it finally managed to pick a free one on a system with only a few free ports so that isn't very practical in such situations.

**Comment by bluejekyll** [comment]
The only reason we don't use port 0 is because I don't believe any OS makes guarantees about the port issuance.

That said, if it's not a risk you are concerned with, maybe we could just have an option that is based in to disable random port selection and only require a new port on each use?

**Comment by Luap99** [comment]
Well to be fair I am not sure but I guess we still like to have randomness.
There is a balance to be made here and I think maybe trying 10 times random and then using 0 is good enough in practice?

**Comment by djc** [comment]
Seems reasonable to try 0 after trying a few random ports -- chances seem good that remaining unused ports are sparsely scattered across the space. Can we reset to trying at random after some time?

**Comment by Luap99** [comment]
I was thinking about doing the bind 0 after the 10 tries always so it doesn't need to store any state to keep track of it. In the worst case it wastes 10 bind syscalls but the overhead of that seems negligible compared to any network latency for the actual requests.

**Comment by Luap99** [comment]
I created a PR https://github.com/hickory-dns/hickory-dns/pull/2260, let me know if you think this makes sense.
