### ISSUE TITLE
TokioAsyncResolver fails with ResolveError { kind: Proto(ProtoError { kind: Io(Kind(ConnectionRefused)) }) }

### ISSUE THREAD

**Issue by zsdsys** [hickory-dns/hickory-dns#2249]
**Describe the bug**
TokioAsyncResolver configured with tls defaults fails with error ConnectionRefused

**To Reproduce**
```
use hickory_resolver::{ *, config::*, name_server::TokioConnectionProvider };

#[tokio::main]
async fn main() {
    let async_resolver = TokioAsyncResolver::new(
        ResolverConfig::cloudflare_tls(),
        ResolverOpts::default(),
        TokioConnectionProvider::default()
    );

    let resolved = async_resolver.lookup_ip("www.cloudflare.com").await.unwrap();
    println!("{:?}", resolved);
}
```

**Expected behavior**
expected to resolve names via dns-over-rustls

**System:**
 - OS: ubuntu
 - Architecture: x86_64
 - Version 22.04
 - rustc version: 1.79.0 (129f3b996 2024-06-10)

**Version:**
Crate: hickory-resolver
Version: { version = "0.24.1", features = ["dns-over-rustls"] }

**Additional context**
using the same code above with ResolverConfig::cloudflare() works as expected (but not secure of course).  

I was also able to debug and it is indeed failing:
2024-06-19 14:06:04.239162 DEBUG hickory_proto::xfer::dns_exchange stream errored while connecting error=io error: tls error: invalid peer certificate: UnknownIssuer

I also attempted to set_tls_client_config with
```
    let mut root_store = RootCertStore::empty();

    root_store.extend(webpki_roots::TLS_SERVER_ROOTS.iter().cloned());

    let config = rustls::ClientConfig
        ::builder()
        .with_root_certificates(root_store)
        .with_no_client_auth();

    let mut resolver_config = ResolverConfig::cloudflare_tls();
    resolver_config.set_tls_client_config(Arc::new(config));  <-- fails
```
but that fails as a rustls::ClientConfig is not a rustls::client::client_conn::ClientConfig and that is now private/inaccessible with newer rustls

**Comment by cpu** [comment]
> Version: { version = "0.24.1", features = ["dns-over-rustls"] }

I suspect you're hitting this issue described in https://github.com/hickory-dns/hickory-dns/issues/2066 and clarified by https://github.com/hickory-dns/hickory-dns/pull/2179 (in the pre-release version only). Try adding the `webpki-roots` feature in addition to `dns-over-rustls`.

> but that fails as a rustls::ClientConfig is not a rustls::client::client_conn::ClientConfig and that is now private/inaccessible with newer rustls

This smells like trying to use a different major version of Rustls than what Hickory-DNS 0.24.1 is using. The error message is confusing, but you shouldn't need to access any private/inaccessible types to resolve this.

**Comment by zsdsys** [comment]
fascinating issue, adding the feature webpki-roots works (I already had that create for other purposes so did not realize that feature)

I am using rustls rustls = { version = "0.23", default-features = false, features = ["ring","std",] }
the issue of rustls::client::client_conn being changed to private has been a real PITA as a lot of code samples I come across

**Comment by cpu** [comment]
> (I already had that create for other purposes so did not realize that feature)

The requirement should be clearer once the fix from https://github.com/hickory-dns/hickory-dns/pull/2179 makes it into a finalized release :crossed_fingers: 

> I am using rustls rustls = { version = "0.23", default-features = false, features = ["ring","std",] }

That would indeed be the problem. hickory-dns 0.24.1 uses rustls 0.21: https://github.com/hickory-dns/hickory-dns/blob/e56a18ee241edf9c8a4ee17508cfc727617ffbb9/Cargo.toml#L64 You would need to do the same for the `ClientConfig` to be compatible.
