### ISSUE TITLE
Are SRV/TXT lookup errors retried?

### ISSUE THREAD

**Issue by isabelatkinson** [hickory-dns/hickory-dns#2263]
Hello! I work on the MongoDB Rust driver, and we are currently investigating whether we should retry SRV/TXT lookup when errors are encountered during client creation. We currently use `TokioAsyncResolver` to perform these lookups. Are there any errors that may occur during lookup (i.e. in [`srv_lookup`](https://docs.rs/hickory-resolver/latest/hickory_resolver/type.TokioAsyncResolver.html#method.srv_lookup) and [`txt_lookup`](https://docs.rs/hickory-resolver/latest/hickory_resolver/type.TokioAsyncResolver.html#method.srv_lookup)) that trigger an internal retry? We want to avoid double-retrying for errors that are already handled by the resolver.

**Comment by djc** [comment]
Have a look at the [`RetryDnsHandle`](https://github.com/hickory-dns/hickory-dns/blob/main/crates/proto/src/xfer/retry_dns_handle.rs#L98) and the [logic](https://github.com/hickory-dns/hickory-dns/blob/main/crates/resolver/src/name_server/name_server_pool.rs#L257) for trying a request against a `NameServerPool`?

**Comment by isabelatkinson** [comment]
Thanks!
