### ISSUE TITLE
Unify integration tests

### ISSUE THREAD

**Issue by divergentdave** [hickory-dns/hickory-dns#2444]
There are currently 29 integration test targets, across all the crates. [This blog post by matklad](https://matklad.github.io/2021/02/27/delete-cargo-integration-tests.html) recommends combining the tests into one integration test target per crate, with multiple submodules holding the various tests. This can decrease test compile time by reducing the number of times the linker has to run, and reduce disk/CI cache usage by eliminating redundancy between many test executables.

**Comment by djc** [comment]
Makes sense.
