### ISSUE TITLE
Are there any ways to set `tls_config` in NameServerConfig from file

### ISSUE THREAD

**Issue by hingbong** [hickory-dns/hickory-dns#2447]
I built the `bin` as a dns forwarder, and I want to set `enable_early_data` to upstreams, but `pub struct TlsClientConfig(pub Arc<ClientConfig>);`, the `Arc` is unable to deserialization from file, are there any ways to set `tls_config` in NameServerConfig from file?

**Comment by djc** [comment]
There is no way to do that currently. Why do you want/need this?

**Comment by hingbong** [comment]
> There is no way to do that currently. Why do you want/need this?

I just want to do some tests

**Comment by djc** [comment]
Okay, well, I'm happy to review a PR for this.

**Comment by hingbong** [comment]
I dont know how to use serde to set this, so I modified source code directly for myself using, haha
