### ISSUE TITLE
What to do about bad referral tests

### ISSUE THREAD

**Issue by marcus0x62** [hickory-dns/hickory-dns#2545]
There are eight tests in the conformance package that test for ServFail responses on referrals to "bad" IP addresses:

1. v4_this_host -> tests for referrals to 0.0.0.0
2. v4_doc -> tests for referrals to 198.51.100.0
3. v4_reserved -> 240.0.0.0
4. v4_link_local -> 169.254.0.1
5. v4_loopback -> 127.0.0.1
6. v4_private_10 -> 10.0.0.1
7. v4_private_172 -> 172.16.0.1
8. v4_private_192 -> 192.168.0.1

Additionally, there are tests in the extended-domain-errors.com suite that test for the same thing.

I think there are a few things to consider about these tests:

1) Today, these tests are all effectively testing the same thing: whether or not Hickory returns ServFail when it does not receive a response from a remote nameserver (or itself in the case of v4_loopback and v4_this_host)  Other than the do_not_query list (which isn't configured in the dns-test config file for Hickory,) there aren't any address limitations I'm aware of in the code right now.

2) Because these tests are essentially testing ServFail on timeout, they can be a bit flaky.  See, for example, [here](https://github.com/hickory-dns/hickory-dns/actions/runs/11628252489/job/32384557267#step:8:226)

3) These tests, as written, will behave differently depending on how someone configures their docker test environment (the address ranges used for container IP assignment, specifically, can overlap with the various addresses used in the test.)

4) I question whether most of these tests are appropriate for a DNS server as such given that in some environments (corporate networks, user's home labs, etc.) some (most, even) of these address ranges will be in use for DNS server infrastructure, and Hickory will need to be able to process referrals to those addresses.  We're testing for behavior that should be blocked on most recursive Internet DNS services, but not by any means all DNS servers (recursive or otherwise.)

I think we should block a few of these addresses explicitly and proactively (127.0.0.1, 0.0.0.0, and, while it currently isn't tested for, 255.255.255.255.) And we should verify in the test suite that referrals are being dropped because they are those IP addresses and not because we don't ever receive a response.

For the others, I think we should have an easy way for users to configure a recommended do_not_query list.  Perhaps having a 'do_not_query = recommended' or something similar for the majority of cases where referrals to RFC 1918 and reserved address ranges are not desirable.  Maybe that should even be the default, and users that don't want that can configure 'disable_recommend_no_query_list = true' or something.

But, otherwise, I think we should drop these tests or constrain them to a configuration where they are all being blocked by explicit do_not_query configurations.

Thoughts?

**Comment by djc** [comment]
> I think we should block a few of these addresses explicitly and proactively (127.0.0.1, 0.0.0.0, and, while it currently isn't tested for, 255.255.255.255.) And we should verify in the test suite that referrals are being dropped because they are those IP addresses and not because we don't ever receive a response.

This makes sense to me. Maybe we can make this more principled by using `IpAddr` methods like `is_broadcast()`, `is_loopback()` and `is_unspecified()`?

> For the others, I think we should have an easy way for users to configure a recommended do_not_query list. Perhaps having a 'do_not_query = recommended' or something similar for the majority of cases where referrals to RFC 1918 and reserved address ranges are not desirable. Maybe that should even be the default, and users that don't want that can configure 'disable_recommend_no_query_list = true' or something.

Sounds like it makes sense to enable this by default, need to carefully design the configuration.
