### ISSUE TITLE
`mdns` feature documented but missing from async-std-resolver crate

### ISSUE THREAD

**Issue by arichtman** [hickory-dns/hickory-dns#2654]
**Describe the bug**

The README notes an mDNS feature [here](https://github.com/hickory-dns/hickory-dns/blob/852e33af6f69bf666e1f4f8a50c003774d85e3d9/crates/async-std-resolver/README.md?plain=1#L19), but no such feature exists [in Cargo.toml](https://github.com/hickory-dns/hickory-dns/blob/852e33af6f69bf666e1f4f8a50c003774d85e3d9/crates/async-std-resolver/Cargo.toml#L27)

**To Reproduce**

```
cargo add async-std-resolver --features mdns
```

**Expected behavior**

Crate is added and feature is active.

**System:**

 - OS: Linux
 - Architecture: x86_64
 - Version: Kernel 6.11.6, Bazzite
 - rustc version: 1.82.0
 
**Version:**

Crate: async-std-resolver
Version: 0.24.1

**Additional context**

async-std-resolver's `Cargo.toml` notes it's not ready but some mDNS code seems to be in the `hickory-resolver` crate, though it also doesn't have any mDNS features in it's `Cargo.toml`

**Comment by djc** [comment]
Unfortunately this amounts to copy/pasta. 9f4d01aae7c73784299b16ef0e1343189a650637 added a README for async-std-resolver, but this particular crate never contained any mdns support (and #2324 removed the mostly disabled support that existed in the resolver crate). At this point we only have some lower-level support in the hickory-proto crate.
