### ISSUE TITLE
hickory-proto 0.24.1 is affected by RUSTSEC-2024-0421

### ISSUE THREAD

**Issue by MarkusPettersson98** [hickory-dns/hickory-dns#2661]
Hello! 

Just want to let you know that the latest release of `hickory-proto` is affected by [RUSTSEC-2024-0421](https://rustsec.org/advisories/RUSTSEC-2024-0421) because of its dependence on `idna 0.4.0`. The solution is to upgrade to `idna 1.0.0` (at least), which was done in the [`0.25.4-alpha.4 release`](https://github.com/hickory-dns/hickory-dns/releases/tag/v0.25.0-alpha.4).

**Comment by djc** [comment]
Yes, we're aware. For now, the recommended mitigation is to upgrade to 0.25.0-alpha.4, although I guess we could probably release a 0.24.2 if there's strong demand for it.

**Comment by svix-jplatte** [comment]
Upgrading to the alpha is only really an option if the only dependency on hickory is your own, rather than an indirect one (e.g. via reqwest's `hickory-dns` feature). A patch release would be appreciated.

**Comment by DDtKey** [comment]
I currently use patched version from my fork, and probably it can be an option to release `0.24.2`?
I've opened a PR just in case https://github.com/hickory-dns/hickory-dns/pull/2662

**Comment by girlbossceo** [comment]
A 0.24.2 release would be appreciated. My project uses 0.24.1 for now as there are some breaking changes in 0.25.0, so we can't upgrade at the moment.

**Comment by MarkusPettersson98** [comment]
We would also appreciate a patch release, even though it is not critical :blush:

**Comment by djc** [comment]
We've released 0.24.2 versions of all the crates. @DDtKey thanks for your efforts on fixing this!
